name = "PlotlySupply"
uuid = "a389b534-8bca-4fe3-8ff2-14829cd8824f"
version = "1.4.0"
authors = ["Jake W. Liu"]

[deps]
BatchAssign = "e837618a-1c15-48db-beb0-68297dffdb28"
ElectronCall = "8ddd578f-0c94-4c64-8c65-f083f291b266"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
MeshGrid = "ebf956a0-ef5e-43be-9fb1-27952996e635"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
BatchAssign = "1.0.0"
ElectronCall = "1.0.0"
Infiltrator = "1.9.3"
MeshGrid = "1.0.4"
PlotlyBase = "0.8.23"
Reexport = "1.2.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
